# action.yaml
name: 'Custom GitHub Action'
description: 'A GitHub Action for Innolab as1'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install packages
      run: pip install .
      shell: bash
    - name: run unit test
      run: python3 test_my_kaya_unittest.py
      shell: bash