name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: test actions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test first action
        id: a1
        uses: ./action.yml # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
